// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6FL-5bj01nsDd9IsZE5DCQgpqv5Sg3fE',
    appId: '1:256276353758:web:f7ed3ae3dcad508e06684f',
    messagingSenderId: '256276353758',
    projectId: 'are-u-82fd0',
    authDomain: 'are-u-82fd0.firebaseapp.com',
    storageBucket: 'are-u-82fd0.firebasestorage.app',
    measurementId: 'G-G7W27GRXJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOPrKdqLNVf0tVUQ0YkaSX23xmETxCIl8',
    appId: '1:256276353758:android:a024c834bee7a7be06684f',
    messagingSenderId: '256276353758',
    projectId: 'are-u-82fd0',
    storageBucket: 'are-u-82fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg3lc6zcDlLAEiqodOOSKhqGlq0_ifY68',
    appId: '1:256276353758:ios:10f310e3554f836706684f',
    messagingSenderId: '256276353758',
    projectId: 'are-u-82fd0',
    storageBucket: 'are-u-82fd0.firebasestorage.app',
    iosClientId: '256276353758-8pu01i25p1s75gi5bcov6ekh2d83f148.apps.googleusercontent.com',
    iosBundleId: 'com.example.appcomplicationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg3lc6zcDlLAEiqodOOSKhqGlq0_ifY68',
    appId: '1:256276353758:ios:10f310e3554f836706684f',
    messagingSenderId: '256276353758',
    projectId: 'are-u-82fd0',
    storageBucket: 'are-u-82fd0.firebasestorage.app',
    iosClientId: '256276353758-8pu01i25p1s75gi5bcov6ekh2d83f148.apps.googleusercontent.com',
    iosBundleId: 'com.example.appcomplicationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6FL-5bj01nsDd9IsZE5DCQgpqv5Sg3fE',
    appId: '1:256276353758:web:5684ceb8e846dd5a06684f',
    messagingSenderId: '256276353758',
    projectId: 'are-u-82fd0',
    authDomain: 'are-u-82fd0.firebaseapp.com',
    storageBucket: 'are-u-82fd0.firebasestorage.app',
    measurementId: 'G-E6LJCG7Y7T',
  );

}