import 'package:appcomplication_app/auth_service.dart';
import 'package:appcomplication_app/screens/login_screen.dart';
import 'package:appcomplication_app/screens/player_selection_screen.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

Future<void> main() async {
  // This is the main entry point of the application.
  // It ensures that all necessary framework bindings are initialized.
  WidgetsFlutterBinding.ensureInitialized();
  
  // It then initializes Firebase with the platform-specific options.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Finally, it runs the main application widget.
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ARE-U',
      debugShowCheckedModeBanner: false, // Hides the debug banner
      theme: ThemeData(
        brightness: Brightness.dark,
        primaryColor: const Color(0xFF6A1B9A), // Deep Purple
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFFDD835), // Sunny Yellow
          brightness: Brightness.dark,
          primary: const Color(0xFFFDD835), // Main button/interactive color
          secondary: const Color(0xFF81C784), // Secondary action color
        ),
        scaffoldBackgroundColor: const Color(0xFF121212), // A pure dark background
        textTheme: const TextTheme(bodyMedium: TextStyle(color: Colors.white, fontSize: 16)),
        useMaterial3: true,
      ),
      // The AuthWrapper is the gatekeeper of the app.
      // It decides whether to show the Login Screen or the Player Selection Screen.
      home: const AuthWrapper(),
    );
  }
}

/// A wrapper that listens to Firebase authentication state changes.
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService.userStream,
      builder: (context, snapshot) {
        // While waiting for the connection, show a loading spinner.
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            backgroundColor: Color(0xFF121212),
            body: Center(child: CircularProgressIndicator(color: Colors.white)),
          );
        }

        // If the user is logged in (including as a guest), show the player selection screen.
        if (snapshot.hasData) {
          return const PlayerSelectionScreen();
        }
        // If the user is logged out, show the login screen.
        else {
          return const LoginScreen();
        }
      },
    );
  }
}
